version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: food_admin
      POSTGRES_PASSWORD: food_password
      POSTGRES_DB: food_rescue_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_food_rescue_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  pgdata:
